workspace:
  base: /go
  path: src/github.com/kowala-tech/drone-plugin-docker

clone:
  git:
    image: plugins/git:next
    pull: true
    tags: true

pipeline:
  build:
    image: golang:1.9
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - go vet ./...
      - go test -cover ./...
      - sh .drone.sh

  publish:
    image: plugins/docker
    repo: endian/drone-docker
    tags: [ "latest" ]
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile
    when:
      branch: master
      event: push
