workspace:
  base: /kowala/workspace
  path: src/github.com/drone-plugins/drone-docker

pipeline:
  build:
    image: kowalatech/go:1.0.1
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - sh .drone.sh

  publish:
    image: plugins/docker
    repo: kowalatech/drone-docker
    tags: [ "latest", "17", "17.12" ]
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile
    when:
      branch: master
      event: push
